#!/usr/bin/env python3
"""
Comprehensive Lab Test Catalog Seeder
Populates the database with 100+ lab tests, templates, and reference ranges.

Usage:
    python3 seed_lab_templates_comprehensive.py

Requirements:
    - Database must be initialized
    - Admin user must exist
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sqlalchemy.orm import Session
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from uuid import uuid4

from app.core.config import settings
from app.models.lab_catalog_models import LabTest
from app.models.lab_template_models import (
    LabTemplate, LabTemplateVersion, LabOptionSet, LabReferenceRange
)
from app.models.user_models import User

SQLALCHEMY_DATABASE_URL = settings.SQLALCHEMY_DATABASE_URL
_connect_args = {"check_same_thread": False} if "sqlite" in SQLALCHEMY_DATABASE_URL else {}
engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args=_connect_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


# =============================================================================
# OPTION SETS
# =============================================================================

def create_option_sets(db: Session):
    """Create reusable option sets for lab tests."""
    print("Creating option sets...")
    
    option_sets_data = {
        # Blood Bank
        "BLOOD_GROUP_OPTIONS": ["A", "B", "AB", "O"],
        "RH_FACTOR": ["Positive", "Negative"],
        "CROSSMATCH_RESULT": ["Compatible", "Incompatible"],
        
        # Urinalysis Dipstick
        "DIPSTICK_PROTEIN": ["Negative", "Trace", "1+", "2+", "3+", "4+"],
        "DIPSTICK_GLUCOSE": ["Negative", "Trace", "1+", "2+", "3+", "4+"],
        "DIPSTICK_KETONES": ["Negative", "Trace", "1+", "2+", "3+"],
        "DIPSTICK_BLOOD": ["Negative", "Trace", "Non-hemolyzed", "Hemolyzed"],
        "DIPSTICK_BILIRUBIN": ["Negative", "1+", "2+", "3+"],
        "DIPSTICK_UROBILINOGEN": ["Normal", "1+", "2+", "3+"],
        "DIPSTICK_NITRITE": ["Negative", "Positive"],
        "DIPSTICK_LEUKOCYTES": ["Negative", "Positive"],
        
        # Microscopy
        "MICROSCOPY_HPF": ["0-1", "1-5", "5-10", "10-20", ">20"],
        "MICROSCOPY_LPF": ["0-1", "1-5", "5-10", "10-20", ">20"],
        
        # Morphology
        "WBC_MORPHOLOGY": ["Normal", "Left Shift", "Toxic Granulation", "Doehle Bodies"],
        "RBC_MORPHOLOGY": ["Normocytic", "Microcytic", "Macrocytic", "Hypochromic", "Anisocytosis", "Poikilocytosis"],
        "PLATELET_MORPHOLOGY": ["Adequate", "Reduced", "Increased", "Clumped"],
        
        # Infectious Disease
        "SICKLING_TEST": ["Negative", "Positive", "Sickle Cell Trait", "Sickle Cell Disease"],
        "MALARIA_RDT": ["Negative", "P. falciparum", "P. vivax", "P. malariae", "P. ovale", "Mixed"],
        "HEPATITIS_B_SURFACE": ["Non-reactive", "Reactive"],
        "HEPATITIS_C_RESULT": ["Non-reactive", "Reactive"],
        "HIV_RESULT": ["Negative", "Positive", "Indeterminate"],
        "SYPHILIS_RESULT": ["Non-reactive", "Reactive"],
        "TYPHOID_RESULT": ["Negative", "Positive", "O:1:80", "O:1:160", "O:1:320", "H:1:80", "H:1:160", "H:1:320"],
        
        # Urine Physical
        "URINE_COLOR": ["Pale Yellow", "Yellow", "Dark Yellow", "Amber", "Brown", "Red", "Green"],
        "URINE_CLARITY": ["Clear", "Slightly Cloudy", "Cloudy", "Turbid"],
        
        # Stool
        "STOOL_CONSISTENCY": ["Formed", "Soft", "Watery", "Mucoid", "Bloody"],
        "STOOL_OCCULT_BLOOD": ["Negative", "Positive"],
        
        # Culture Results
        "CULTURE_GROWTH": ["No Growth", "Mixed Growth", "Scanty", "Light", "Moderate", "Heavy"],
        "BACTERIA_IDENTIFIED": ["E. coli", "Klebsiella spp.", "Proteus spp.", "Pseudomonas aeruginosa", 
                                "Staphylococcus aureus", "Streptococcus spp.", "Enterococcus spp.", 
                                "Salmonella spp.", "Shigella spp.", "Candida spp.", "Other"],
        
        # Thyroid
        "TSH_RESULT": ["Normal", "Low", "High"],
        
        # Coagulation
        "PT_RESULT": ["Normal", "Prolonged"],
        "PTT_RESULT": ["Normal", "Prolonged"],
    }
    
    for code, options in option_sets_data.items():
        existing = db.query(LabOptionSet).filter(LabOptionSet.code == code).first()
        if not existing:
            obj = LabOptionSet(code=code, options_json=options)
            db.add(obj)
    
    db.commit()
    print(f"Created {len(option_sets_data)} option sets")


# =============================================================================
# COMPREHENSIVE LAB TESTS DATA
# =============================================================================

def get_all_tests_data():
    """Return comprehensive list of all lab tests."""
    
    tests = [
        # ==================== HEMATOLOGY ====================
        {
            "test_name": "Complete Blood Count (CBC)",
            "test_code": "CBC",
            "test_category": "Hematology",
            "test_type": "Panel",
            "description": "Complete blood count with differential - comprehensive blood analysis",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2-3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "stat_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "HEM001",
        },
        {
            "test_name": "Peripheral Blood Smear",
            "test_code": "PBS",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Microscopic examination of blood cells morphology",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM002",
        },
        {
            "test_name": "Erythrocyte Sedimentation Rate (ESR)",
            "test_code": "ESR",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Non-specific marker of inflammation",
            "specimen_type": "Sodium Citrate Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM003",
        },
        {
            "test_name": "Reticulocyte Count",
            "test_code": "RETIC",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Assessment of bone marrow function",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 8,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "HEM004",
        },
        {
            "test_name": "Sickle Cell Test",
            "test_code": "SICKLE",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Screening test for sickle cell disease and trait",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM005",
        },
        {
            "test_name": "Hemoglobin Electrophoresis",
            "test_code": "HBE",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Hemoglobin variant analysis for thalassemia and hemoglobinopathies",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "3 mL",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "HEM006",
        },
        {
            "test_name": "Prothrombin Time (PT)",
            "test_code": "PT",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Assessment of extrinsic coagulation pathway",
            "specimen_type": "Sodium Citrate Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM007",
        },
        {
            "test_name": "Activated Partial Thromboplastin Time (APTT)",
            "test_code": "APTT",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Assessment of intrinsic coagulation pathway",
            "specimen_type": "Sodium Citrate Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM008",
        },
        {
            "test_name": "INR (International Normalized Ratio)",
            "test_code": "INR",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Standardized coagulation monitoring for warfarin therapy",
            "specimen_type": "Sodium Citrate Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM009",
        },
        {
            "test_name": "Coagulation Profile (PT, APTT, INR)",
            "test_code": "COAG",
            "test_category": "Hematology",
            "test_type": "Panel",
            "description": "Complete coagulation screening panel",
            "specimen_type": "Sodium Citrate Plasma",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM010",
        },
        {
            "test_name": "D-Dimer",
            "test_code": "DDIMER",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Fibrin degradation product for thrombosis workup",
            "specimen_type": "Sodium Citrate Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 8,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "HEM011",
        },
        {
            "test_name": "Fibrinogen",
            "test_code": "FIB",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Coagulation factor I assessment",
            "specimen_type": "Sodium Citrate Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 8,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "HEM012",
        },
        {
            "test_name": "Direct Coombs Test (DAT) - Blood Bank",
            "test_code": "DATBB",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Detection of antibodies on red blood cells",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "3 mL",
            "routine_tat": 8,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "HEM013",
        },
        {
            "test_name": "Indirect Coombs Test (IAT)",
            "test_code": "IAT",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Antibody screen for transfusion compatibility",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 8,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "HEM014",
        },
        {
            "test_name": "Platelet Count",
            "test_code": "PLT",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Quantitative platelet assessment",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "HEM015",
        },
        {
            "test_name": "Iron Studies (Iron, Ferritin, TIBC)",
            "test_code": "IRON",
            "test_category": "Hematology",
            "test_type": "Panel",
            "description": "Iron deficiency anemia workup",
            "specimen_type": "Serum",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM016",
        },
        {
            "test_name": "Serum Ferritin",
            "test_code": "FERRITIN",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Body iron stores assessment",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM017",
        },
        {
            "test_name": "Serum Iron",
            "test_code": "FE",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Current circulating iron",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM018",
        },
        {
            "test_name": "Total Iron Binding Capacity (TIBC)",
            "test_code": "TIBC",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Iron binding capacity assessment",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM019",
        },
        {
            "test_name": "Vitamin B12",
            "test_code": "B12",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Megaloblastic anemia workup",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM020",
        },
        {
            "test_name": "Folate",
            "test_code": "FOLATE",
            "test_category": "Hematology",
            "test_type": "Individual",
            "description": "Folic acid level assessment",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "HEM021",
        },

        # ==================== CLINICAL CHEMISTRY ====================
        {
            "test_name": "Liver Function Tests (LFT)",
            "test_code": "LFT",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Comprehensive liver function assessment",
            "specimen_type": "Serum",
            "specimen_volume": "5 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "stat_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM001",
        },
        {
            "test_name": "Renal Function Tests (RFT)",
            "test_code": "RFT",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Kidney function assessment",
            "specimen_type": "Serum",
            "specimen_volume": "5 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "stat_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM002",
        },
        {
            "test_name": "Lipid Profile",
            "test_code": "LIPID",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Cardiovascular risk assessment - Cholesterol, Triglycerides, HDL, LDL",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "5 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM003",
        },
        {
            "test_name": "Fasting Blood Glucose",
            "test_code": "FBG",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Blood sugar assessment",
            "specimen_type": "Sodium Fluoride Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "stat_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "CHEM004",
        },
        {
            "test_name": "Random Blood Glucose",
            "test_code": "RBG",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Random blood sugar check",
            "specimen_type": "Sodium Fluoride Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM005",
        },
        {
            "test_name": "Postprandial Blood Glucose (PPBG)",
            "test_code": "PPBG",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "2-hour post-meal blood sugar",
            "specimen_type": "Sodium Fluoride Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM006",
        },
        {
            "test_name": "HbA1c (Glycated Hemoglobin)",
            "test_code": "HbA1c",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Long-term diabetes control marker (3-month average)",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "CHEM007",
        },
        {
            "test_name": "Oral Glucose Tolerance Test (OGTT)",
            "test_code": "OGTT",
            "test_category": "Chemistry",
            "test_type": "Profile",
            "description": "Diabetes diagnostic test",
            "specimen_type": "Sodium Fluoride Plasma",
            "specimen_volume": "Multiple samples",
            "routine_tat": 4,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM008",
        },
        {
            "test_name": "Serum Electrolytes (Na, K, Cl, HCO3)",
            "test_code": "ELECT",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Electrolyte balance assessment",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "stat_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "CHEM009",
        },
        {
            "test_name": "Sodium (Na+)",
            "test_code": "NA",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum sodium level",
            "specimen_type": "Serum",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM010",
        },
        {
            "test_name": "Potassium (K+)",
            "test_code": "K",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum potassium level",
            "specimen_type": "Serum",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM011",
        },
        {
            "test_name": "Chloride (Cl-)",
            "test_code": "CL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum chloride level",
            "specimen_type": "Serum",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM012",
        },
        {
            "test_name": "Bicarbonate (HCO3)",
            "test_code": "HCO3",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum bicarbonate level",
            "specimen_type": "Serum",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM013",
        },
        {
            "test_name": "Total Cholesterol",
            "test_code": "CHOL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Total cholesterol level",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM014",
        },
        {
            "test_name": "Triglycerides",
            "test_code": "TG",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Triglyceride level",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM015",
        },
        {
            "test_name": "HDL Cholesterol",
            "test_code": "HDL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "High-density lipoprotein",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM016",
        },
        {
            "test_name": "LDL Cholesterol",
            "test_code": "LDL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Low-density lipoprotein",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM017",
        },
        {
            "test_name": "VLDL Cholesterol",
            "test_code": "VLDL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Very low-density lipoprotein",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM018",
        },
        {
            "test_name": "Total Bilirubin",
            "test_code": "TBIL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Total bilirubin level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM019",
        },
        {
            "test_name": "Direct Bilirubin",
            "test_code": "DBIL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Conjugated bilirubin level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM020",
        },
        {
            "test_name": "Indirect Bilirubin",
            "test_code": "IBIL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Unconjugated bilirubin level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM021",
        },
        {
            "test_name": "Alanine Aminotransferase (ALT)",
            "test_code": "ALT",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Liver enzyme - hepatocellular injury marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM022",
        },
        {
            "test_name": "Aspartate Aminotransferase (AST)",
            "test_code": "AST",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Liver enzyme - hepatocellular injury marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM023",
        },
        {
            "test_name": "Alkaline Phosphatase (ALP)",
            "test_code": "ALP",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Liver enzyme - cholestasis marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM024",
        },
        {
            "test_name": "Gamma-Glutamyl Transferase (GGT)",
            "test_code": "GGT",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Liver enzyme - cholestasis marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM025",
        },
        {
            "test_name": "Total Protein",
            "test_code": "TP",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Total protein level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM026",
        },
        {
            "test_name": "Serum Albumin",
            "test_code": "ALB",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum albumin level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM027",
        },
        {
            "test_name": "Serum Globulin",
            "test_code": "GLOB",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum globulin level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM028",
        },
        {
            "test_name": "A/G Ratio",
            "test_code": "AGRATIO",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Albumin/Globulin ratio",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM029",
        },
        {
            "test_name": "Urea",
            "test_code": "UREA",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Kidney function marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM030",
        },
        {
            "test_name": "Creatinine",
            "test_code": "CREAT",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Kidney function marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "stat_tat": 1,
            "nhis_covered": True,
            "nhis_code": "CHEM031",
        },
        {
            "test_name": "Estimated GFR (eGFR)",
            "test_code": "EGFR",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Estimated glomerular filtration rate",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM032",
        },
        {
            "test_name": "Uric Acid",
            "test_code": "UA",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Gout and kidney function marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM033",
        },
        {
            "test_name": "Calcium",
            "test_code": "CA",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum calcium level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM034",
        },
        {
            "test_name": "Phosphorus",
            "test_code": "PHOS",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum phosphorus level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM035",
        },
        {
            "test_name": "Magnesium",
            "test_code": "MG",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Serum magnesium level",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM036",
        },
        {
            "test_name": "Amylase",
            "test_code": "AMYL",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Pancreatic enzyme - acute pancreatitis marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM037",
        },
        {
            "test_name": "Lipase",
            "test_code": "LIPASE",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Pancreatic enzyme - acute pancreatitis marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM038",
        },
        {
            "test_name": "Creatine Kinase (CK)",
            "test_code": "CK",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Muscle injury marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM039",
        },
        {
            "test_name": "Lactate Dehydrogenase (LDH)",
            "test_code": "LDH",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Tissue damage marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 6,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM040",
        },
        {
            "test_name": "C-Reactive Protein (CRP)",
            "test_code": "CRP",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Inflammation marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 8,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "CHEM041",
        },
        {
            "test_name": "High Sensitivity CRP (hs-CRP)",
            "test_code": "HSCRP",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Cardiovascular risk assessment",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "CHEM042",
        },

        # ==================== THYROID FUNCTION ====================
        {
            "test_name": "Thyroid Stimulating Hormone (TSH)",
            "test_code": "TSH",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Thyroid function screening",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "THY001",
        },
        {
            "test_name": "Free T4 (fT4)",
            "test_code": "FT4",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Active thyroid hormone",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "THY002",
        },
        {
            "test_name": "Free T3 (fT3)",
            "test_code": "FT3",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Active thyroid hormone",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "THY003",
        },
        {
            "test_name": "Total T4",
            "test_code": "TT4",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Total thyroxine",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "THY004",
        },
        {
            "test_name": "Total T3",
            "test_code": "TT3",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Total triiodothyronine",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "THY005",
        },
        {
            "test_name": "Thyroid Profile (TSH, fT4)",
            "test_code": "THYPROF",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Basic thyroid function panel",
            "specimen_type": "Serum",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "THY006",
        },

        # ==================== URINALYSIS ====================
        {
            "test_name": "Urinalysis (Complete)",
            "test_code": "UA",
            "test_category": "Urinalysis",
            "test_type": "Panel",
            "description": "Complete urinalysis - physical, chemical, microscopic",
            "specimen_type": "Urine (Mid-stream)",
            "specimen_volume": "10-20 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "stat_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "URINE001",
        },
        {
            "test_name": "Urine Dipstick",
            "test_code": "UADIP",
            "test_category": "Urinalysis",
            "test_type": "Individual",
            "description": "Urine chemistry using dipstick",
            "specimen_type": "Urine (Fresh)",
            "specimen_volume": "5 mL",
            "routine_tat": 1,
            "urgent_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "URINE002",
        },
        {
            "test_name": "Urine Microscopy",
            "test_code": "UAMIC",
            "test_category": "Urinalysis",
            "test_type": "Individual",
            "description": "Microscopic examination of urine",
            "specimen_type": "Urine (Mid-stream)",
            "specimen_volume": "10 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "URINE003",
        },
        {
            "test_name": "Urine Culture & Sensitivity",
            "test_code": "UCULT",
            "test_category": "Urinalysis",
            "test_type": "Culture",
            "description": "Bacterial culture and antibiotic sensitivity",
            "specimen_type": "Urine (Mid-stream/Catheter)",
            "specimen_volume": "10 mL",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "URINE004",
        },
        {
            "test_name": "Urine Protein/Creatinine Ratio",
            "test_code": "UPCR",
            "test_category": "Urinalysis",
            "test_type": "Individual",
            "description": "Proteinuria quantification",
            "specimen_type": "Urine (Spot)",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "URINE005",
        },
        {
            "test_name": "Urine Albumin/Creatinine Ratio (UACR)",
            "test_code": "UACR",
            "test_category": "Urinalysis",
            "test_type": "Individual",
            "description": "Microalbuminuria screening for diabetic nephropathy",
            "specimen_type": "Urine (Spot)",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "URINE006",
        },
        {
            "test_name": "24-Hour Urine Protein",
            "test_code": "24UP",
            "test_category": "Urinalysis",
            "test_type": "Individual",
            "description": "Quantitative protein in 24-hour urine collection",
            "specimen_type": "24-Hour Urine",
            "specimen_volume": "Complete collection",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "URINE007",
        },

        # ==================== BLOOD BANK ====================
        {
            "test_name": "Blood Grouping (ABO & Rh)",
            "test_code": "BG",
            "test_category": "Blood Bank",
            "test_type": "Individual",
            "description": "ABO and Rhesus blood group determination",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "stat_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "BB001",
        },
        {
            "test_name": "Blood Group (ABO only)",
            "test_code": "ABO",
            "test_category": "Blood Bank",
            "test_type": "Individual",
            "description": "ABO blood group only",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "BB002",
        },
        {
            "test_name": "Rh Factor",
            "test_code": "RH",
            "test_category": "Blood Bank",
            "test_type": "Individual",
            "description": "Rhesus factor determination",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 2,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "BB003",
        },
        {
            "test_name": "Crossmatch",
            "test_code": "XM",
            "test_category": "Blood Bank",
            "test_type": "Individual",
            "description": "Compatibility testing for transfusion",
            "specimen_type": "EDTA Whole Blood + Donor Unit",
            "specimen_volume": "5 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "stat_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "BB004",
        },
        {
            "test_name": "Antibody Screen",
            "test_code": "ABSCR",
            "test_category": "Blood Bank",
            "test_type": "Individual",
            "description": "Screening for irregular antibodies",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "BB005",
        },
        {
            "test_name": "Direct Antiglobulin Test (DAT)",
            "test_code": "DAT",
            "test_category": "Blood Bank",
            "test_type": "Individual",
            "description": "Detection of in-vivo antibody coating on RBCs",
            "specimen_type": "EDTA Whole Blood",
            "specimen_volume": "2 mL",
            "routine_tat": 4,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "BB006",
        },

        # ==================== MICROBIOLOGY ====================
        {
            "test_name": "Blood Culture",
            "test_code": "BCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial/fungal culture from blood",
            "specimen_type": "Blood (Aerobic + Anaerobic)",
            "specimen_volume": "10 mL (adult), 2-5 mL (pediatric)",
            "routine_tat": 120,
            "urgent_tat": 48,
            "nhis_covered": True,
            "nhis_code": "MICRO001",
        },
        {
            "test_name": "Blood Culture (Pediatric)",
            "test_code": "BCULTP",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial/fungal culture from blood (pediatric)",
            "specimen_type": "Blood (Pediatric bottle)",
            "specimen_volume": "2-5 mL",
            "routine_tat": 120,
            "urgent_tat": 48,
            "nhis_covered": True,
            "nhis_code": "MICRO002",
        },
        {
            "test_name": "Stool Culture",
            "test_code": "SCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture for enteric pathogens",
            "specimen_type": "Fresh Stool",
            "specimen_volume": "5-10 g",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO003",
        },
        {
            "test_name": "Stool Microscopy (Ova & Cysts)",
            "test_code": "SMIC",
            "test_category": "Microbiology",
            "test_type": "Microscopy",
            "description": "Parasitology examination",
            "specimen_type": "Fresh Stool",
            "specimen_volume": "5 g",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "MICRO004",
        },
        {
            "test_name": "Stool Occult Blood",
            "test_code": "FOBT",
            "test_category": "Microbiology",
            "test_type": "Individual",
            "description": "Fecal occult blood test for GI bleeding",
            "specimen_type": "Stool",
            "specimen_volume": "Small amount",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "MICRO005",
        },
        {
            "test_name": "Sputum Culture",
            "test_code": "SPCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from sputum",
            "specimen_type": "Morning Sputum",
            "specimen_volume": "5 mL",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO006",
        },
        {
            "test_name": "Sputum for AFB",
            "test_code": "AFB",
            "test_category": "Microbiology",
            "test_type": "Microscopy",
            "description": "Acid-fast bacilli stain for tuberculosis",
            "specimen_type": "Morning Sputum",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "MICRO007",
        },
        {
            "test_name": "Wound Swab Culture",
            "test_code": "WCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from wound",
            "specimen_type": "Swab in transport medium",
            "specimen_volume": "1 swab",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO008",
        },
        {
            "test_name": "Throat Swab Culture",
            "test_code": "TCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from throat",
            "specimen_type": "Swab",
            "specimen_volume": "1 swab",
            "routine_tat": 48,
            "urgent_tat": 12,
            "nhis_covered": True,
            "nhis_code": "MICRO009",
        },
        {
            "test_name": "Ear Swab Culture",
            "test_code": "ECULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from ear",
            "specimen_type": "Swab",
            "specimen_volume": "1 swab",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO010",
        },
        {
            "test_name": "Eye Swab Culture",
            "test_code": "EYECULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from eye",
            "specimen_type": "Swab",
            "specimen_volume": "1 swab",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO011",
        },
        {
            "test_name": "Vaginal Swab Culture",
            "test_code": "VCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from vagina",
            "specimen_type": "Swab",
            "specimen_volume": "1 swab",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO012",
        },
        {
            "test_name": "Urethral Swab Culture",
            "test_code": "UCULT",
            "test_category": "Microbiology",
            "test_type": "Culture",
            "description": "Bacterial culture from urethra",
            "specimen_type": "Swab",
            "specimen_volume": "1 swab",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "MICRO013",
        },
        {
            "test_name": "CSF Analysis",
            "test_code": "CSF",
            "test_category": "Microbiology",
            "test_type": "Profile",
            "description": "Cerebrospinal fluid analysis - cell count, protein, glucose, culture",
            "specimen_type": "CSF",
            "specimen_volume": "2-3 mL",
            "routine_tat": 24,
            "urgent_tat": 2,
            "nhis_covered": True,
            "nhis_code": "MICRO014",
        },
        {
            "test_name": "Pleural Fluid Analysis",
            "test_code": "PLEURAL",
            "test_category": "Microbiology",
            "test_type": "Profile",
            "description": "Pleural fluid analysis - cell count, chemistry, culture",
            "specimen_type": "Pleural Fluid",
            "specimen_volume": "10 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "MICRO015",
        },
        {
            "test_name": "Ascitic Fluid Analysis",
            "test_code": "ASCITIC",
            "test_category": "Microbiology",
            "test_type": "Profile",
            "description": "Ascitic fluid analysis",
            "specimen_type": "Ascitic Fluid",
            "specimen_volume": "10 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "MICRO016",
        },

        # ==================== SEROLOGY / IMMUNOLOGY ====================
        {
            "test_name": "HIV 1 & 2 (Rapid)",
            "test_code": "HIV",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "HIV screening test",
            "specimen_type": "Whole Blood/Serum/Plasma",
            "specimen_volume": "2 mL",
            "routine_tat": 1,
            "urgent_tat": 0.5,
            "stat_tat": 0.25,
            "nhis_covered": True,
            "nhis_code": "SER001",
        },
        {
            "test_name": "HIV Confirmation (Western Blot)",
            "test_code": "HIVWB",
            "test_category": "Serology",
            "test_type": "Confirmation",
            "description": "HIV confirmation test",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "SER002",
        },
        {
            "test_name": "Hepatitis B Surface Antigen (HBsAg)",
            "test_code": "HBSAG",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Hepatitis B infection marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "SER003",
        },
        {
            "test_name": "Hepatitis B Surface Antibody (HBsAb)",
            "test_code": "HBSAB",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Immunity to Hepatitis B",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "SER004",
        },
        {
            "test_name": "Hepatitis B e Antigen (HBeAg)",
            "test_code": "HBEAG",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "HBV replication marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER005",
        },
        {
            "test_name": "Hepatitis B e Antibody (HBeAb)",
            "test_code": "HBEAB",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "HBV replication marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER006",
        },
        {
            "test_name": "Hepatitis B Core Antibody (HBcAb)",
            "test_code": "HBCAB",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "HBV infection marker (IgM/IgG)",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER007",
        },
        {
            "test_name": "Hepatitis C Antibody",
            "test_code": "HCV",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Hepatitis C screening",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "SER008",
        },
        {
            "test_name": "Typhoid (Widal Test)",
            "test_code": "WIDAL",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Salmonella typhi antibody detection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "SER009",
        },
        {
            "test_name": "Typhoid (IDEXX)",
            "test_code": "TYPIDXX",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Rapid typhoid test",
            "specimen_type": "Whole Blood/Serum",
            "specimen_volume": "2 mL",
            "routine_tat": 1,
            "urgent_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "SER010",
        },
        {
            "test_name": "Syphilis (VDRL/RPR)",
            "test_code": "VDRL",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Syphilis screening",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "SER011",
        },
        {
            "test_name": "Syphilis (TPHA) - Confirmation",
            "test_code": "TPHA",
            "test_category": "Serology",
            "test_type": "Confirmation",
            "description": "Syphilis confirmation",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER012",
        },
        {
            "test_name": "Malaria Rapid Diagnostic Test (RDT)",
            "test_code": "MALRDT",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Rapid malaria antigen detection",
            "specimen_type": "Capillary Whole Blood",
            "specimen_volume": "5 μL",
            "routine_tat": 1,
            "urgent_tat": 0.5,
            "stat_tat": 0.25,
            "nhis_covered": True,
            "nhis_code": "SER013",
        },
        {
            "test_name": "Malaria Blood Smear",
            "test_code": "MALBS",
            "test_category": "Parasitology",
            "test_type": "Microscopy",
            "description": "Malaria parasite identification",
            "specimen_type": "Thick & Thin Blood Film",
            "specimen_volume": "Blood films",
            "routine_tat": 2,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "PARA001",
        },
        {
            "test_name": "Dengue NS1 Antigen",
            "test_code": "DENGNS1",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Dengue early detection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "SER014",
        },
        {
            "test_name": "Dengue IgM Antibody",
            "test_code": "DENGIGM",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Recent dengue infection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER015",
        },
        {
            "test_name": "Dengue IgG Antibody",
            "test_code": "DENGIGG",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Past dengue infection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER016",
        },
        {
            "test_name": "Rubella IgG",
            "test_code": "RUBIGG",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Rubella immunity status",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER017",
        },
        {
            "test_name": "Rubella IgM",
            "test_code": "RUBIGM",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Recent rubella infection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER018",
        },
        {
            "test_name": "Toxoplasma IgG",
            "test_code": "TOXIGG",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Toxoplasma immunity",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER019",
        },
        {
            "test_name": "Toxoplasma IgM",
            "test_code": "TOXIGM",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Recent toxoplasma infection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER020",
        },
        {
            "test_name": "CMV IgG",
            "test_code": "CMVIGG",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Cytomegalovirus immunity",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER021",
        },
        {
            "test_name": "CMV IgM",
            "test_code": "CMVIGM",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Recent CMV infection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER022",
        },
        {
            "test_name": "ASO Titer",
            "test_code": "ASO",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Streptococcus pyogenes antibody",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER023",
        },
        {
            "test_name": "Rheumatoid Factor (RF)",
            "test_code": "RF",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Rheumatoid arthritis marker",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER024",
        },
        {
            "test_name": "Anti-CCP (Anti-Cyclic Citrullinated Peptide)",
            "test_code": "CCP",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "Rheumatoid arthritis diagnostic",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "SER025",
        },
        {
            "test_name": "ANA (Anti-Nuclear Antibody)",
            "test_code": "ANA",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "Autoimmune screening",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "SER026",
        },
        {
            "test_name": "COVID-19 Antigen",
            "test_code": "COVIDAG",
            "test_category": "Serology",
            "test_type": "Screening",
            "description": "SARS-CoV-2 antigen detection",
            "specimen_type": "Nasopharyngeal Swab",
            "specimen_volume": "1 swab",
            "routine_tat": 1,
            "urgent_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "SER027",
        },
        {
            "test_name": "COVID-19 Antibody",
            "test_code": "COVIDAB",
            "test_category": "Serology",
            "test_type": "Individual",
            "description": "SARS-CoV-2 antibody detection",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "SER028",
        },

        # ==================== PREGNANCY TESTS ====================
        {
            "test_name": "Pregnancy Test (Urine)",
            "test_code": "PREGU",
            "test_category": "Chemistry",
            "test_type": "Screening",
            "description": "Urine hCG pregnancy test",
            "specimen_type": "Urine (Morning)",
            "specimen_volume": "10 mL",
            "routine_tat": 1,
            "urgent_tat": 0.5,
            "nhis_covered": True,
            "nhis_code": "PREGN001",
        },
        {
            "test_name": "Serum Beta hCG",
            "test_code": "BHCG",
            "test_category": "Chemistry",
            "test_type": "Individual",
            "description": "Quantitative pregnancy test",
            "specimen_type": "Serum",
            "specimen_volume": "3 mL",
            "routine_tat": 4,
            "urgent_tat": 1,
            "nhis_covered": True,
            "nhis_code": "PREGN002",
        },

        # ==================== SPECIAL PROFILES ====================
        {
            "test_name": "Antenatal Profile 1",
            "test_code": "ANP1",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "First antenatal booking profile",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "PROF001",
        },
        {
            "test_name": "Antenatal Profile 2",
            "test_code": "ANP2",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "Repeat antenatal profile",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "PROF002",
        },
        {
            "test_name": "Pre-operative Profile",
            "test_code": "PREOP",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "Surgical clearance profile",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 24,
            "urgent_tat": 4,
            "stat_tat": 2,
            "nhis_covered": True,
            "nhis_code": "PROF003",
        },
        {
            "test_name": "Fever Profile",
            "test_code": "FEVER",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "Fever workup panel",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 48,
            "urgent_tat": 12,
            "nhis_covered": True,
            "nhis_code": "PROF004",
        },
        {
            "test_name": "Diabetes Profile",
            "test_code": "DIAB",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "Diabetes monitoring profile",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "PROF005",
        },
        {
            "test_name": "Hypertension Profile",
            "test_code": "HTN",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "Hypertension workup",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "PROF006",
        },
        {
            "test_name": "Extended Lipid Profile",
            "test_code": "ELIPID",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Comprehensive lipid assessment",
            "specimen_type": "Serum (Fasting)",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "CHEM043",
        },
        {
            "test_name": "Extended Liver Function Tests",
            "test_code": "ELFT",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Comprehensive liver function",
            "specimen_type": "Serum",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "CHEM044",
        },
        {
            "test_name": "Extended Renal Function Tests",
            "test_code": "ERFT",
            "test_category": "Chemistry",
            "test_type": "Panel",
            "description": "Comprehensive kidney function",
            "specimen_type": "Serum",
            "specimen_volume": "5 mL",
            "routine_tat": 24,
            "urgent_tat": 4,
            "nhis_covered": True,
            "nhis_code": "CHEM045",
        },
        {
            "test_name": "Arthritis Profile",
            "test_code": "ARTH",
            "test_category": "Profile",
            "test_type": "Panel",
            "description": "Arthritis workup panel",
            "specimen_type": "Multiple",
            "specimen_volume": "Multiple",
            "routine_tat": 72,
            "urgent_tat": 24,
            "nhis_covered": True,
            "nhis_code": "PROF007",
        },
    ]
    
    return tests


# =============================================================================
# REFERENCE RANGES
# =============================================================================

def get_reference_ranges_data():
    """Return comprehensive reference ranges by parameter."""
    return [
        # CBC Parameters
        {"field_code": "hb", "sex": "M", "low": 13.0, "high": 17.5, "unit": "g/dL", "description": "Hemoglobin Male"},
        {"field_code": "hb", "sex": "F", "low": 11.5, "high": 16.0, "unit": "g/dL", "description": "Hemoglobin Female"},
        {"field_code": "hct", "sex": "M", "low": 40.0, "high": 54.0, "unit": "%", "description": "Hematocrit Male"},
        {"field_code": "hct", "sex": "F", "low": 36.0, "high": 48.0, "unit": "%", "description": "Hematocrit Female"},
        {"field_code": "rbc_count", "sex": "ANY", "low": 4.0, "high": 6.0, "unit": "x10^12/L", "description": "RBC Count"},
        {"field_code": "wbc_count", "sex": "ANY", "low": 4.0, "high": 11.0, "unit": "x10^9/L", "description": "WBC Count"},
        {"field_code": "platelet_count", "sex": "ANY", "low": 150, "high": 450, "unit": "x10^9/L", "description": "Platelet Count"},
        {"field_code": "mcv", "sex": "ANY", "low": 80.0, "high": 100.0, "unit": "fL", "description": "Mean Corpuscular Volume"},
        {"field_code": "mch", "sex": "ANY", "low": 27.0, "high": 33.0, "unit": "pg", "description": "Mean Corpuscular Hemoglobin"},
        {"field_code": "mchc", "sex": "ANY", "low": 32.0, "high": 36.0, "unit": "g/dL", "description": "Mean Corpuscular Hemoglobin Concentration"},
        {"field_code": "neutrophils", "sex": "ANY", "low": 40.0, "high": 75.0, "unit": "%", "description": "Neutrophils"},
        {"field_code": "lymphocytes", "sex": "ANY", "low": 20.0, "high": 45.0, "unit": "%", "description": "Lymphocytes"},
        {"field_code": "monocytes", "sex": "ANY", "low": 2.0, "high": 10.0, "unit": "%", "description": "Monocytes"},
        {"field_code": "eosinophils", "sex": "ANY", "low": 1.0, "high": 6.0, "unit": "%", "description": "Eosinophils"},
        {"field_code": "basophils", "sex": "ANY", "low": 0.0, "high": 2.0, "unit": "%", "description": "Basophils"},
        
        # ESR
        {"field_code": "esr", "sex": "M", "low": 0.0, "high": 15.0, "unit": "mm/hr", "description": "ESR Male"},
        {"field_code": "esr", "sex": "F", "low": 0.0, "high": 20.0, "unit": "mm/hr", "description": "ESR Female"},
        
        # Chemistry - Liver
        {"field_code": "alt", "sex": "ANY", "low": 0.0, "high": 40.0, "unit": "U/L", "description": "ALT"},
        {"field_code": "ast", "sex": "ANY", "low": 0.0, "high": 40.0, "unit": "U/L", "description": "AST"},
        {"field_code": "alp", "sex": "ANY", "low": 44.0, "high": 147.0, "unit": "U/L", "description": "Alkaline Phosphatase"},
        {"field_code": "ggt", "sex": "M", "low": 0.0, "high": 55.0, "unit": "U/L", "description": "GGT Male"},
        {"field_code": "ggt", "sex": "F", "low": 0.0, "high": 38.0, "unit": "U/L", "description": "GGT Female"},
        {"field_code": "tbil", "sex": "ANY", "low": 0.0, "high": 21.0, "unit": "μmol/L", "description": "Total Bilirubin"},
        {"field_code": "dbil", "sex": "ANY", "low": 0.0, "high": 8.0, "unit": "μmol/L", "description": "Direct Bilirubin"},
        {"field_code": "tp", "sex": "ANY", "low": 60.0, "high": 80.0, "unit": "g/L", "description": "Total Protein"},
        {"field_code": "alb", "sex": "ANY", "low": 35.0, "high": 55.0, "unit": "g/L", "description": "Albumin"},
        
        # Chemistry - Kidney
        {"field_code": "urea", "sex": "ANY", "low": 2.9, "high": 8.2, "unit": "mmol/L", "description": "Urea"},
        {"field_code": "creat", "sex": "M", "low": 62.0, "high": 115.0, "unit": "μmol/L", "description": "Creatinine Male"},
        {"field_code": "creat", "sex": "F", "low": 53.0, "high": 97.0, "unit": "μmol/L", "description": "Creatinine Female"},
        {"field_code": "egfr", "sex": "M", "low": 90.0, "high": 120.0, "unit": "mL/min/1.73m²", "description": "eGFR Male"},
        {"field_code": "egfr", "sex": "F", "low": 90.0, "high": 120.0, "unit": "mL/min/1.73m²", "description": "eGFR Female"},
        
        # Chemistry - Electrolytes
        {"field_code": "na", "sex": "ANY", "low": 136.0, "high": 145.0, "unit": "mmol/L", "description": "Sodium"},
        {"field_code": "k", "sex": "ANY", "low": 3.5, "high": 5.0, "unit": "mmol/L", "description": "Potassium"},
        {"field_code": "cl", "sex": "ANY", "low": 98.0, "high": 106.0, "unit": "mmol/L", "description": "Chloride"},
        {"field_code": "hco3", "sex": "ANY", "low": 22.0, "high": 29.0, "unit": "mmol/L", "description": "Bicarbonate"},
        
        # Chemistry - Lipids
        {"field_code": "chol", "sex": "ANY", "low": 0.0, "high": 5.2, "unit": "mmol/L", "description": "Total Cholesterol"},
        {"field_code": "tg", "sex": "ANY", "low": 0.0, "high": 1.7, "unit": "mmol/L", "description": "Triglycerides"},
        {"field_code": "hdl", "sex": "M", "low": 1.0, "high": 1.9, "unit": "mmol/L", "description": "HDL Male"},
        {"field_code": "hdl", "sex": "F", "low": 1.2, "high": 2.2, "unit": "mmol/L", "description": "HDL Female"},
        {"field_code": "ldl", "sex": "ANY", "low": 0.0, "high": 3.4, "unit": "mmol/L", "description": "LDL Cholesterol"},
        
        # Chemistry - Glucose
        {"field_code": "fbg", "sex": "ANY", "low": 3.9, "high": 6.1, "unit": "mmol/L", "description": "Fasting Blood Glucose"},
        {"field_code": "rbg", "sex": "ANY", "low": 3.9, "high": 7.8, "unit": "mmol/L", "description": "Random Blood Glucose"},
        {"field_code": "hba1c", "sex": "ANY", "low": 4.0, "high": 6.0, "unit": "%", "description": "HbA1c"},
        
        # Chemistry - Minerals
        {"field_code": "ca", "sex": "ANY", "low": 2.1, "high": 2.6, "unit": "mmol/L", "description": "Calcium"},
        {"field_code": "phos", "sex": "ANY", "low": 0.8, "high": 1.5, "unit": "mmol/L", "description": "Phosphorus"},
        {"field_code": "mg", "sex": "ANY", "low": 0.7, "high": 1.1, "unit": "mmol/L", "description": "Magnesium"},
        {"field_code": "ua", "sex": "M", "low": 150.0, "high": 440.0, "unit": "μmol/L", "description": "Uric Acid Male"},
        {"field_code": "ua", "sex": "F", "low": 90.0, "high": 360.0, "unit": "μmol/L", "description": "Uric Acid Female"},
        
        # Chemistry - Enzymes
        {"field_code": "amyl", "sex": "ANY", "low": 28.0, "high": 100.0, "unit": "U/L", "description": "Amylase"},
        {"field_code": "lipase", "sex": "ANY", "low": 13.0, "high": 60.0, "unit": "U/L", "description": "Lipase"},
        {"field_code": "ck", "sex": "M", "low": 38.0, "high": 174.0, "unit": "U/L", "description": "CK Male"},
        {"field_code": "ck", "sex": "F", "low": 26.0, "high": 140.0, "unit": "U/L", "description": "CK Female"},
        {"field_code": "ldh", "sex": "ANY", "low": 140.0, "high": 280.0, "unit": "U/L", "description": "LDH"},
        
        # Thyroid
        {"field_code": "tsh", "sex": "ANY", "low": 0.4, "high": 4.0, "unit": "mIU/L", "description": "TSH"},
        {"field_code": "ft4", "sex": "ANY", "low": 9.0, "high": 25.0, "unit": "pmol/L", "description": "Free T4"},
        {"field_code": "ft3", "sex": "ANY", "low": 3.5, "high": 6.5, "unit": "pmol/L", "description": "Free T3"},
        
        # Coagulation
        {"field_code": "pt", "sex": "ANY", "low": 11.0, "high": 13.5, "unit": "seconds", "description": "Prothrombin Time"},
        {"field_code": "aptt", "sex": "ANY", "low": 25.0, "high": 35.0, "unit": "seconds", "description": "APTT"},
        {"field_code": "inr", "sex": "ANY", "low": 0.8, "high": 1.2, "unit": "ratio", "description": "INR"},
        
        # Urinalysis
        {"field_code": "urine_ph", "sex": "ANY", "low": 4.5, "high": 8.0, "unit": "pH", "description": "Urine pH"},
        {"field_code": "urine_sg", "sex": "ANY", "low": 1.005, "high": 1.030, "unit": "SG", "description": "Urine Specific Gravity"},
    ]


# =============================================================================
# MAIN SEEDING FUNCTION
# =============================================================================

def seed_comprehensive_lab_catalog():
    """Main function to seed comprehensive lab catalog."""
    print("=" * 70)
    print("COMPREHENSIVE LAB TEST CATALOG SEEDER")
    print("=" * 70)
    
    db = SessionLocal()
    try:
        # Get admin user
        admin_user = db.query(User).filter(User.username == "admin").first()
        if not admin_user:
            print("ERROR: Admin user not found. Run init_db.py first.")
            return
        
        admin_user_id = admin_user.id
        print(f"Using admin user ID: {admin_user_id}")
        
        # Create option sets
        create_option_sets(db)
        
        # Get all tests data
        tests_data = get_all_tests_data()
        print(f"\nProcessing {len(tests_data)} lab tests...")
        
        # Create lab tests in catalog
        created_count = 0
        updated_count = 0
        skipped_count = 0
        
        for test_data in tests_data:
            existing = db.query(LabTest).filter(LabTest.test_code == test_data["test_code"]).first()
            
            if existing:
                # Update existing test
                for key, value in test_data.items():
                    if key not in ["test_code"]:
                        setattr(existing, key, value)
                existing.is_active = True
                updated_count += 1
            else:
                # Create new test
                test = LabTest(**test_data)
                db.add(test)
                created_count += 1
            
            # Commit each test individually to handle duplicates properly
            try:
                db.commit()
            except Exception as e:
                db.rollback()
                # If there's still an error (e.g., duplicate), skip this test
                skipped_count += 1
                print(f"  Skipped test {test_data['test_code']}: {str(e)[:50]}")
        
        print(f"Created: {created_count} new tests")
        print(f"Updated: {updated_count} existing tests")
        print(f"Skipped: {skipped_count} tests (duplicates)")
        print(f"Total: {len(tests_data)} lab tests in catalog")
        
        # Create reference ranges
        print("\nCreating reference ranges...")
        ranges_data = get_reference_ranges_data()
        
        for range_data in ranges_data:
            existing = db.query(LabReferenceRange).filter(
                LabReferenceRange.field_code == range_data["field_code"],
                LabReferenceRange.sex == range_data["sex"]
            ).first()
            
            if not existing:
                db_range = LabReferenceRange(
                    field_code=range_data["field_code"],
                    sex=range_data["sex"],
                    low=range_data.get("low"),
                    high=range_data.get("high"),
                    unit=range_data.get("unit"),
                    text_range=range_data.get("text_range")
                )
                db.add(db_range)
        
        db.commit()
        print(f"Created {len(ranges_data)} reference ranges")
        
        print("\n" + "=" * 70)
        print("SEEDING COMPLETED SUCCESSFULLY!")
        print("=" * 70)
        print(f"\nSummary:")
        print(f"  - Total Lab Tests: {len(tests_data)}")
        print(f"  - Reference Ranges: {len(ranges_data)}")
        print(f"  - Categories: Hematology, Chemistry, Serology, Microbiology, Urinalysis, Blood Bank, Profiles")
        
    except Exception as e:
        print(f"ERROR: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_comprehensive_lab_catalog()
