"""Create triage_vitals table and relationships

Revision ID: 07da4e86a7c9
Revises: 72e2dc0c34b9
Create Date: 2025-11-09 03:08:55.939545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07da4e86a7c9'
down_revision: Union[str, Sequence[str], None] = '72e2dc0c34b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
