"""mawuli_pc

Revision ID: 2091a86885bd
Revises: 53e1c97d2944
Create Date: 2025-12-17 12:41:43.951908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2091a86885bd'
down_revision: Union[str, Sequence[str], None] = '53e1c97d2944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discharge_clearances_id'), table_name='discharge_clearances')
    op.drop_table('discharge_clearances')
    op.alter_column('charge_payments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_charge_payments_charge_id'), table_name='charge_payments')
    op.drop_index(op.f('ix_charge_payments_payment_id'), table_name='charge_payments')
    op.drop_index(op.f('ix_charges_admission'), table_name='charges')
    op.drop_index(op.f('ix_charges_opd_visit'), table_name='charges')
    op.drop_index(op.f('ix_encounters_admission'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_opd_visit'), table_name='encounters')
    op.drop_index(op.f('ix_invoices_admission'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_opd_visit'), table_name='invoices')
    op.drop_index(op.f('ix_lab_orders_admission'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_opd_visit'), table_name='lab_orders')
    op.drop_index(op.f('ix_opd_visits_patient'), table_name='opd_visits')
    op.drop_index(op.f('ix_opd_visits_visit_date'), table_name='opd_visits')
    op.drop_constraint(op.f('opd_visits_opd_number_key'), 'opd_visits', type_='unique')
    op.drop_index(op.f('ix_prescriptions_admission'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_opd_visit'), table_name='prescriptions')
    op.drop_index(op.f('ix_radiology_orders_admission'), table_name='radiology_orders')
    op.drop_index(op.f('ix_radiology_orders_opd_visit'), table_name='radiology_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_radiology_orders_opd_visit'), 'radiology_orders', ['opd_visit_id'], unique=False)
    op.create_index(op.f('ix_radiology_orders_admission'), 'radiology_orders', ['admission_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_opd_visit'), 'prescriptions', ['opd_visit_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_admission'), 'prescriptions', ['admission_id'], unique=False)
    op.create_unique_constraint(op.f('opd_visits_opd_number_key'), 'opd_visits', ['opd_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_opd_visits_visit_date'), 'opd_visits', ['visit_date'], unique=False)
    op.create_index(op.f('ix_opd_visits_patient'), 'opd_visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_opd_visit'), 'lab_orders', ['opd_visit_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_admission'), 'lab_orders', ['admission_id'], unique=False)
    op.create_index(op.f('ix_invoices_opd_visit'), 'invoices', ['opd_visit_id'], unique=False)
    op.create_index(op.f('ix_invoices_admission'), 'invoices', ['admission_id'], unique=False)
    op.create_index(op.f('ix_encounters_opd_visit'), 'encounters', ['opd_visit_id'], unique=False)
    op.create_index(op.f('ix_encounters_admission'), 'encounters', ['admission_id'], unique=False)
    op.create_index(op.f('ix_charges_opd_visit'), 'charges', ['opd_visit_id'], unique=False)
    op.create_index(op.f('ix_charges_admission'), 'charges', ['admission_id'], unique=False)
    op.create_index(op.f('ix_charge_payments_payment_id'), 'charge_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_charge_payments_charge_id'), 'charge_payments', ['charge_id'], unique=False)
    op.alter_column('charge_payments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_table('discharge_clearances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_cleared', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('payment_cleared_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_cleared_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nursing_cleared', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('nursing_cleared_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nursing_cleared_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nursing_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_discharge_clearances_admission_id_admissions')),
    sa.ForeignKeyConstraint(['nursing_cleared_by_id'], ['users.id'], name=op.f('fk_discharge_clearances_nursing_cleared_by_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_discharge_clearances_patient_id_patients')),
    sa.ForeignKeyConstraint(['payment_cleared_by_id'], ['users.id'], name=op.f('fk_discharge_clearances_payment_cleared_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('discharge_clearances_pkey')),
    sa.UniqueConstraint('admission_id', name=op.f('uq_discharge_clearances_admission_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_discharge_clearances_id'), 'discharge_clearances', ['id'], unique=False)
    # ### end Alembic commands ###
