"""add_expenses_procedures_languages_antenatal

Revision ID: 2bc8e96bc3a4
Revises: bc2236aa83b4
Create Date: 2025-11-12 14:09:03.866693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc8e96bc3a4'
down_revision: Union[str, Sequence[str], None] = 'bc2236aa83b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SUPPLIES', 'EQUIPMENT', 'MAINTENANCE', 'UTILITIES', 'SALARIES', 'MEDICATIONS', 'LAB_SUPPLIES', 'RADIOLOGY_SUPPLIES', 'ADMINISTRATIVE', 'MARKETING', 'TRAINING', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('vendor_contact', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'REJECTED', 'CANCELLED', name='expensestatus'), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('expense_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_path', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('ordered_by_id', sa.Integer(), nullable=False),
    sa.Column('procedure_number', sa.String(length=50), nullable=False),
    sa.Column('procedure_name', sa.String(length=200), nullable=False),
    sa.Column('procedure_code', sa.String(length=50), nullable=True),
    sa.Column('procedure_type', sa.Enum('SURGICAL', 'NON_SURGICAL', 'DIAGNOSTIC', 'THERAPEUTIC', 'MINOR', 'MAJOR', name='proceduretype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='procedurestatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=100), nullable=True),
    sa.Column('anesthesia_provider', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_id'), 'procedures', ['id'], unique=False)
    op.create_index(op.f('ix_procedures_procedure_number'), 'procedures', ['procedure_number'], unique=True)
    op.add_column('patients', sa.Column('languages_spoken', sa.String(), nullable=True))
    # Add ANTENATAL to ChargeType enum
    op.execute("ALTER TYPE chargetype ADD VALUE IF NOT EXISTS 'antenatal'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'languages_spoken')
    op.drop_index(op.f('ix_procedures_procedure_number'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_id'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
