"""Create patients table for registration module

Revision ID: 82cc700994b4
Revises: e91a23e0fee9
Create Date: 2025-11-09 01:56:12.743814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cc700994b4'
down_revision: Union[str, Sequence[str], None] = 'e91a23e0fee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('patients', sa.Column('national_id', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_patients_upi'), table_name='patients')
    op.create_index(op.f('ix_patients_first_name'), 'patients', ['first_name'], unique=False)
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_patients_national_id'), 'patients', ['national_id'], unique=True)
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=False)
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'dob')
    op.drop_column('patients', 'upi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('upi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_national_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_first_name'), table_name='patients')
    op.create_index(op.f('ix_patients_upi'), 'patients', ['upi'], unique=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patients', 'is_active')
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'phone_number')
    op.drop_column('patients', 'national_id')
    op.drop_column('patients', 'date_of_birth')
    # ### end Alembic commands ###
