"""add inventory management lab sample tracking and qc models

Revision ID: 84ee1ecdd1bc
Revises: 1cb013f601f8
Create Date: 2025-11-09 21:33:00.001146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84ee1ecdd1bc'
down_revision: Union[str, Sequence[str], None] = '1cb013f601f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first (PostgreSQL requirement)
    # Using DO blocks to check if type exists before creating
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE stockstatus AS ENUM ('in_stock', 'low_stock', 'out_of_stock', 'expired', 'discontinued');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE transactiontype AS ENUM ('purchase', 'sale', 'adjustment', 'return', 'expiry', 'damage', 'transfer');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE samplestatus AS ENUM ('collected', 'received', 'processing', 'completed', 'rejected', 'expired');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE qcstatus AS ENUM ('pending', 'passed', 'failed', 'out_of_range');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('medication_code', sa.String(length=50), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_nhis_covered', sa.Boolean(), nullable=True),
    sa.Column('nhis_code', sa.String(length=50), nullable=True),
    sa.Column('is_formulary', sa.Boolean(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_medication_code'), 'medications', ['medication_code'], unique=True)
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=False)
    op.create_table('reference_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('normal_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('normal_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('critical_low', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('critical_high', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_ranges_id'), 'reference_ranges', ['id'], unique=False)
    op.create_index(op.f('ix_reference_ranges_test_code'), 'reference_ranges', ['test_code'], unique=False)
    op.create_index(op.f('ix_reference_ranges_test_name'), 'reference_ranges', ['test_name'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication1_id', sa.Integer(), nullable=False),
    sa.Column('medication2_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication1_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['medication2_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_interactions_id'), 'drug_interactions', ['id'], unique=False)
    op.create_table('formulary_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('medication_category', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulary_rules_id'), 'formulary_rules', ['id'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('manufacturing_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('in_stock', 'low_stock', 'out_of_stock', 'expired', 'discontinued', name='stockstatus', create_type=False), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_batch_number'), 'stock_items', ['batch_number'], unique=False)
    op.create_index(op.f('ix_stock_items_id'), 'stock_items', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('purchase', 'sale', 'adjustment', 'return', 'expiry', 'damage', 'transfer', name='transactiontype', create_type=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('lab_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_order_id', sa.Integer(), nullable=False),
    sa.Column('collected_by_id', sa.Integer(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('barcode_type', sa.String(length=50), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('collection_method', sa.String(length=100), nullable=True),
    sa.Column('collection_site', sa.String(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('collected', 'received', 'processing', 'completed', 'rejected', 'expired', name='samplestatus', create_type=False), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('storage_temperature', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_samples_barcode'), 'lab_samples', ['barcode'], unique=True)
    op.create_index(op.f('ix_lab_samples_id'), 'lab_samples', ['id'], unique=False)
    op.create_table('qc_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_order_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('qc_type', sa.String(length=100), nullable=False),
    sa.Column('qc_test_name', sa.String(length=255), nullable=False),
    sa.Column('equipment_name', sa.String(length=255), nullable=True),
    sa.Column('reagent_lot', sa.String(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'passed', 'failed', 'out_of_range', name='qcstatus', create_type=False), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('deviation', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('deviation_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lower_limit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('upper_limit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_records_id'), 'qc_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_records_id'), table_name='qc_records')
    op.drop_table('qc_records')
    op.drop_index(op.f('ix_lab_samples_id'), table_name='lab_samples')
    op.drop_index(op.f('ix_lab_samples_barcode'), table_name='lab_samples')
    op.drop_table('lab_samples')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_stock_items_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_batch_number'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_formulary_rules_id'), table_name='formulary_rules')
    op.drop_table('formulary_rules')
    op.drop_index(op.f('ix_drug_interactions_id'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index(op.f('ix_reference_ranges_test_name'), table_name='reference_ranges')
    op.drop_index(op.f('ix_reference_ranges_test_code'), table_name='reference_ranges')
    op.drop_index(op.f('ix_reference_ranges_id'), table_name='reference_ranges')
    op.drop_table('reference_ranges')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_medication_code'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS qcstatus')
    op.execute('DROP TYPE IF EXISTS samplestatus')
    op.execute('DROP TYPE IF EXISTS transactiontype')
    op.execute('DROP TYPE IF EXISTS stockstatus')
    # ### end Alembic commands ###
