"""add_drug_administrations_table

Revision ID: a46a659383dc
Revises: 7f54e88b4c00
Create Date: 2025-11-14 00:12:59.875459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a46a659383dc'
down_revision: Union[str, Sequence[str], None] = '7f54e88b4c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('administered_by_id', sa.Integer(), nullable=False),
    sa.Column('administration_time', sa.DateTime(), nullable=False),
    sa.Column('dosage_given', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_administrations_id'), 'drug_administrations', ['id'], unique=False)
    op.drop_index('ix_medication_administrations_id', table_name='medication_administrations')
    op.drop_table('medication_administrations')
    op.alter_column('lab_orders', 'is_walk_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('procedures', 'is_walk_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('radiology_orders', 'is_walk_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radiology_orders', 'is_walk_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('procedures', 'is_walk_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('lab_orders', 'is_walk_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('medication_administrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('administered_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('medication_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dosage_given', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('route', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('administered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('frequency_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('frequency_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patient_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adverse_reaction', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('adverse_reaction_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], name='medication_administrations_administered_by_id_fkey'),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name='medication_administrations_admission_id_fkey'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name='medication_administrations_medication_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='medication_administrations_patient_id_fkey'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name='medication_administrations_prescription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='medication_administrations_pkey')
    )
    op.create_index('ix_medication_administrations_id', 'medication_administrations', ['id'], unique=False)
    op.drop_index(op.f('ix_drug_administrations_id'), table_name='drug_administrations')
    op.drop_table('drug_administrations')
    # ### end Alembic commands ###
