"""add_medication_administration_table

Revision ID: bc2236aa83b4
Revises: ef41500e9f15
Create Date: 2025-11-12 12:48:20.025230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2236aa83b4'
down_revision: Union[str, Sequence[str], None] = 'ef41500e9f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('administered_by_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('medication_code', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('dosage_given', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('administered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('frequency_type', sa.String(length=50), nullable=True),
    sa.Column('frequency_interval', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('patient_response', sa.Text(), nullable=True),
    sa.Column('adverse_reaction', sa.Boolean(), nullable=True, server_default='false'),
    sa.Column('adverse_reaction_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administrations_id'), 'medication_administrations', ['id'], unique=False)
    op.drop_constraint('admissions_admission_number_key', 'admissions', type_='unique')
    op.create_index(op.f('ix_image_annotations_id'), 'image_annotations', ['id'], unique=False)
    op.drop_constraint('insurance_providers_code_key', 'insurance_providers', type_='unique')
    op.drop_constraint('insurance_providers_name_key', 'insurance_providers', type_='unique')
    op.drop_index('idx_reset_token', table_name='password_reset_tokens')
    op.drop_index('idx_reset_user', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.drop_index('ix_prescriptions_medication_id', table_name='prescriptions')
    op.drop_constraint('fk_prescriptions_medication_id_medications', 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'medications', ['medication_id'], ['id'])
    op.drop_constraint('ward_types_code_key', 'ward_types', type_='unique')
    op.drop_constraint('ward_types_name_key', 'ward_types', type_='unique')
    op.drop_constraint('wards_name_key', 'wards', type_='unique')
    op.drop_constraint('wards_ward_number_key', 'wards', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wards_ward_number_key', 'wards', ['ward_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('wards_name_key', 'wards', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('ward_types_name_key', 'ward_types', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('ward_types_code_key', 'ward_types', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key('fk_prescriptions_medication_id_medications', 'prescriptions', 'medications', ['medication_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_prescriptions_medication_id', 'prescriptions', ['medication_id'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.create_index('idx_reset_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('idx_reset_token', 'password_reset_tokens', ['token'], unique=True)
    op.create_unique_constraint('insurance_providers_name_key', 'insurance_providers', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('insurance_providers_code_key', 'insurance_providers', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_image_annotations_id'), table_name='image_annotations')
    op.create_unique_constraint('admissions_admission_number_key', 'admissions', ['admission_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_medication_administrations_id'), table_name='medication_administrations')
    op.drop_table('medication_administrations')
    # ### end Alembic commands ###
