"""restructure appointments: create queue and scheduled appointments tables

Revision ID: restructure_appointments
Revises: latest
Create Date: 2026-01-07 13:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'restructure_appointments'
down_revision = '31350ee33b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create scheduled_appointments table
    op.create_table('scheduled_appointments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=True),
        sa.Column('patient_name', sa.String(length=255), nullable=True),
        sa.Column('patient_phone', sa.String(length=20), nullable=True),
        sa.Column('assigned_doctor_id', sa.Integer(), nullable=False),
        sa.Column('appointment_date', sa.DateTime(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=True, default=30),
        sa.Column('reason_complaint', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'RESCHEDULED', name='scheduledappointmentstatus'), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True, default=5),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_appointments_id'), 'scheduled_appointments', ['id'], unique=False)
    
    # Create opd_queue table (rename from appointments)
    op.create_table('opd_queue',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('department', sa.String(length=100), nullable=False),
        sa.Column('department_type', sa.String(length=20), nullable=True, default='opd'),
        sa.Column('assigned_clinician_id', sa.Integer(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('visit_type', sa.Enum('WALK_IN', 'EMERGENCY', 'FOLLOW_UP', name='visittype'), nullable=False, default='walk_in'),
        sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='queuestatus'), nullable=False, default='waiting'),
        sa.Column('priority', sa.Integer(), nullable=True, default=5),
        sa.Column('queue_number', sa.Integer(), nullable=True),
        sa.Column('checked_in_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('chief_complaint', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_clinician_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opd_queue_id'), 'opd_queue', ['id'], unique=False)
    
    # Drop foreign key constraint from encounters table temporarily
    op.execute('ALTER TABLE encounters DROP CONSTRAINT IF EXISTS encounters_appointment_id_fkey')
    
    # Migrate data from appointments table to opd_queue table
    op.execute("""
        INSERT INTO opd_queue (
            id, patient_id, department, department_type, assigned_clinician_id, 
            created_by_id, priority, queue_number, checked_in_at, started_at, 
            completed_at, chief_complaint, notes, is_active, created_at, updated_at
        )
        SELECT 
            id, patient_id, department, department_type, assigned_clinician_id,
            created_by_id, priority, queue_number, checked_in_at, started_at,
            completed_at, chief_complaint, notes, is_active, created_at, updated_at
        FROM appointments
    """)
    
    # Add new foreign key constraint to encounters table pointing to opd_queue
    op.execute('ALTER TABLE encounters ADD COLUMN queue_entry_id INTEGER REFERENCES opd_queue(id)')
    
    # Update encounters to reference queue_entry_id instead of appointment_id
    op.execute('UPDATE encounters SET queue_entry_id = appointment_id WHERE appointment_id IS NOT NULL')
    
    # Drop the old appointment_id column
    op.execute('ALTER TABLE encounters DROP COLUMN appointment_id')
    
    # Drop the old appointments table
    op.drop_table('appointments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recreate the old appointments table
    op.create_table('appointments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('department', sa.String(length=100), nullable=False),
        sa.Column('department_type', sa.String(length=20), nullable=True, default='opd'),
        sa.Column('assigned_clinician_id', sa.Integer(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('appointment_type', sa.Enum('WALK_IN', 'SCHEDULED', 'EMERGENCY', 'FOLLOW_UP', name='appointmenttype'), nullable=False),
        sa.Column('status', sa.Enum('SCHEDULED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True, default=5),
        sa.Column('scheduled_date', sa.DateTime(), nullable=False),
        sa.Column('checked_in_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('chief_complaint', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.String(length=1000), nullable=True),
        sa.Column('queue_number', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_clinician_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    
    # Migrate data back from opd_queue to appointments
    op.execute("""
        INSERT INTO appointments (
            id, patient_id, department, department_type, assigned_clinician_id,
            created_by_id, appointment_type, status, priority, scheduled_date,
            checked_in_at, started_at, completed_at, chief_complaint, notes,
            queue_number, is_active, created_at, updated_at
        )
        SELECT 
            id, patient_id, department, department_type, assigned_clinician_id,
            created_by_id, 'walk_in'::appointmenttype, 
            CASE 
                WHEN status = 'WAITING'::queuestatus THEN 'SCHEDULED'::appointmentstatus
                WHEN status = 'IN_PROGRESS'::queuestatus THEN 'IN_PROGRESS'::appointmentstatus
                WHEN status = 'COMPLETED'::queuestatus THEN 'COMPLETED'::appointmentstatus
                WHEN status = 'CANCELLED'::queuestatus THEN 'CANCELLED'::appointmentstatus
                WHEN status = 'NO_SHOW'::queuestatus THEN 'NO_SHOW'::appointmentstatus
                ELSE 'SCHEDULED'::appointmentstatus
            END,
            priority, created_at, checked_in_at, started_at, completed_at,
            chief_complaint, notes, queue_number, is_active, created_at, updated_at
        FROM opd_queue
    """)
    
    # Add appointment_id column back to encounters
    op.execute('ALTER TABLE encounters ADD COLUMN appointment_id INTEGER REFERENCES appointments(id)')
    
    # Update encounters to reference appointment_id instead of queue_entry_id
    op.execute('UPDATE encounters SET appointment_id = queue_entry_id WHERE queue_entry_id IS NOT NULL')
    
    # Drop the queue_entry_id column
    op.execute('ALTER TABLE encounters DROP COLUMN queue_entry_id')
    
    # Drop the new tables
    op.drop_table('opd_queue')
    op.drop_table('scheduled_appointments')
    
    # ### end Alembic commands ###
